import type { Metadata } from 'next';
import '@/styles/globals.scss';
import { UpProvider } from '@/components/upProvider';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'LUKSO MiniApp Nextjs Template',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          
      <body><Providers>
      <UpProvider>{children}</UpProvider>
      </Providers></body>
      
    </html>
  );
}
